name: Build And Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd src && \
          docker build . -t minichambre/wordpress:latest
      - run: |
          docker login --username ${{ secrets.USER }} --password ${{ secrets.PASSWORD }}
          docker push minichambre/wordpress:latest